### Registrar administrador
# @name registerAdmin
POST http://localhost:3000/api/auth/register-admin
Content-Type: application/json

{
  "nome": "Admin Principal",
  "email": "queirozdouglas466@gmail.com",
  "password": "Dv.23456",
  "cpf": "12345678901",
  "cns": "123456789012345",
  "dataNascimento": "1980-01-01",
  "sexo": "MASCULINO",
  "racaCor": "BRANCA",
  "escolaridade": "SUPERIOR",
  "endereco": {
    "logradouro": "Rua Exemplo",
    "numero": "123",
    "bairro": "Centro",
    "cidade": "São Paulo",
    "estado": "SP",
    "cep": "12345678"
  },
  "telefone": "11987654321",
  "adminSecret": "SuperSecretAdmin123"
}

### Login de administrador
# @name loginAdmin
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "queirozdouglas466@gmail.com",
  "password": "Dv.23456"
}

###
@accessToken={{loginAdmin.response.body.access_token}}
@refreshToken={{loginAdmin.response.body.refresh_token}}

### Refresh token
# @name refreshToken
POST http://localhost:3000/api/auth/refresh
Content-Type: application/json

{
  "refresh_token": "tiq3vcaawtqz"
}

### Registrar enfermeiro
# @name deactivateEmployee
POST http://localhost:3000/api/auth/deactivate/{{enfermeiroId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "motivo": "Demissão por reestruturação da equipe"
}