### Criar Consulta (Médico)
POST https://sistema-hospitalar.onrender.com/api/consultas
Content-Type: application/json
Authorization: Bearer {{medico_token}}

{
    "pacienteId": "{{paciente_id}}",
    "unidadeSaudeId": "{{unidade_saude_id}}",
    "observacoes": "Paciente com tosse persistente e febre baixa. Prescrito antibiótico.",
    "cid10": "J45"
}

> {%
    client.global.set("consulta_id", response.body.id);
%}

###

### Obter Consulta (Médico)
GET https://sistema-hospitalar.onrender.com/api/consultas/{{consulta_id}}
Authorization: Bearer {{medico_token}}

###

### Obter Consulta (Enfermeiro)
GET https://sistema-hospitalar.onrender.com/api/consultas/{{consulta_id}}
Authorization: Bearer {{enfermeiro_token}}

###

### Listar Consultas por Paciente (Médico)
GET https://sistema-hospitalar.onrender.com/api/consultas/pacientes/{{paciente_id}}
Authorization: Bearer {{medico_token}}

###

### Listar Consultas por Paciente (Enfermeiro)
GET https://sistema-hospitalar.onrender.com/api/consultas/pacientes/{{paciente_id}}
Authorization: Bearer {{enfermeiro_token}}

###

### Atualizar Consulta (Médico)
PUT https://sistema-hospitalar.onrender.com/api/consultas/{{consulta_id}}
Content-Type: application/json
Authorization: Bearer {{medico_token}}

{
  "observacoes": "Paciente apresentou melhora após 5 dias de antibiótico. Mantida medicação.",
  "cid10": "J45.0"
}

###

### Deletar Consulta (Médico)
DELETE https://sistema-hospitalar.onrender.com/api/consultas/{{consulta_id}}
Authorization: Bearer {{medico_token}}

###

### Listar Consultas por Profissional (Administrador)
GET https://sistema-hospitalar.onrender.com/api/consultas/profissional/{{medico_id}}
Authorization: Bearer {{admin_token}}

###

### Listar Atendimentos Ativos por Unidade (Administrador)
GET https://sistema-hospitalar.onrender.com/api/consultas/unidade/{{unidade_saude_id}}/atendimentos-ativos
Authorization: Bearer {{admin_token}}

###

### Listar Consultas por Unidade (Administrador)
GET https://sistema-hospitalar.onrender.com/api/consultas/unidade/{{unidade_saude_id}}
Authorization: Bearer {{admin_token}}