### Criar Enfermeiro
POST http://localhost:3000/api/enfermeiros
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "João Santos",
  "cpf": "09245682345",
  "cns": "937203894572163",
  "dataNascimento": "1990-08-20",
  "sexo": "MASCULINO",
  "racaCor": "PARDA",
  "escolaridade": "POS_GRADUACAO",
  "endereco": {
    "logradouro": "Avenida Paulista",
    "numero": "1500",
    "bairro": "Bela Vista",
    "cidade": "São Paulo",
    "estado": "SP",
    "cep": "01310000"
  },
  "telefone": "88996384623",
  "email": "dev.queiroz05@gmail.com",
  "senha": "Dv.23456",
  "dataContratacao": "2023-03-15",
  "coren": "974302-PB",
  "unidadeSaudeId": "e86a55e8-f4d2-4c02-87f5-424912d097d2"
}

### Obter Enfermeiro
GET http://localhost:3000/api/enfermeiros/a444cffe-cd41-4011-b74b-83e6f0cf7710
Authorization: Bearer {{token}}

### Listar Enfermeiros
GET http://localhost:3000/api/enfermeiros
Authorization: Bearer {{token}}

###

### Atualizar Enfermeiro
PUT http://localhost:3000/api/enfermeiros/a444cffe-cd41-4011-b74b-83e6f0cf7710
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Maria Silva Atualizada",
  "coren": "654321-SP",
  "dataContratacao": "2023-02-01"
}

### Deletar Enfermeiro
DELETE http://localhost:3000/api/enfermeiros/{{enfermeiro_id}}
Authorization: Bearer {{token}}

### Login Enfermeiro (Obter Token para Testar Rotas como Enfermeiro)
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "dev.queiroz05@gmail.com",
  "password": "Dv.23456"
}

### Obter Próprio Enfermeiro (como Enfermeiro)
GET http://localhost:3000/api/enfermeiros/{{enfermeiro_id}}
Authorization: Bearer {{token}}
