### Criar Médico
POST https://sistema-hospitalar.onrender.com/api/medicos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Pedro Oliveira",
  "cpf": "98765432109",
  "cns": "987654321098765",
  "dataNascimento": "1980-03-15",
  "sexo": "MASCULINO",
  "racaCor": "BRANCA",
  "escolaridade": "SUPERIOR",
  "endereco":
    {
      "logradouro": "Avenida da Saúde",
      "numero": "450",
      "bairro": "Jardim América",
      "cidade": "São Paulo",
      "estado": "SP",
      "cep": "04532000"
    },
    "telefone": "11977776666",
    "email": "douglas.queiroz4@aluno.ce.gov.br",
    "senha": "Dv.23456",
    "dataContratacao": "2023-03-15",
    "crm": "54321-SP",
    "unidadeSaudeId": "e86a55e8-f4d2-4c02-87f5-424912d097d2"
}

### Listar Médicos
GET https://sistema-hospitalar.onrender.com/api/medicos
Authorization: Bearer {{token}}

### Listar Médico por ID
GET https://sistema-hospitalar.onrender.com/api/medicos/{{medico_id}}
Authorization: Bearer {{token}}

### Atualizar Médico
PUT https://sistema-hospitalar.onrender.com/api/medicos/{{medico_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "João Santos Atualizado",
  "crm": "54321-SP",
  "dataContratacao": "2023-02-01"
}

### Deletar Médico
DELETE https://sistema-hospitalar.onrender.com/api/medicos/{{medico_id}}
Authorization: Bearer {{token}}

### Login Médico (Obter Token para Testar Rotas como Médico)
POST https://sistema-hospitalar.onrender.com/api/auth/login
Content-Type: application/json

{
  "email": "douglas.queiroz4@aluno.ce.gov.br",
  "password": "Dv.23456"
}

### Obter Próprio Médico (como Médico)
GET https://sistema-hospitalar.onrender.com/api/medicos/{{medico_id}}
Authorization: Bearer {{token}}

### Listar Médicos (como Médico)
GET https://sistema-hospitalar.onrender.com/api/medicos
Authorization: Bearer {{token}}