### Criar Médico
POST http://localhost:3000/api/medicos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6Imorc1l4RmljVjBqenZmL0kiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2djeXNyaHZ0Ym9iZWt1enBzZnd1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2Y2ZkZWFkNS1jMTI4LTRlMDEtYjQwMC01YWI5NzRlZTFlOGEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ2OTkyNDM3LCJpYXQiOjE3NDY5ODg4MzcsImVtYWlsIjoicXVlaXJvemRvdWdsYXM0NjZAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InF1ZWlyb3pkb3VnbGFzNDY2QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJub21lIjoiRG91Z2xhcyBRdWVpcm96IiwicGFwZWwiOiJBRE1JTklTVFJBRE9SX1BSSU5DSVBBTCIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNmNmZGVhZDUtYzEyOC00ZTAxLWI0MDAtNWFiOTc0ZWUxZThhIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NDY5ODg4Mzd9XSwic2Vzc2lvbl9pZCI6ImFhYjdmN2U3LTgxZTYtNGQ3Yi04ZDdhLTI5NDVhMTk4ZGE5NiIsImlzX2Fub255bW91cyI6ZmFsc2V9.xJ3QTT26NDdZnRay4WjMjjnx4rJNW1nwswGk5_bnRzs

{
  "nome": "Pedro Oliveira",
  "cpf": "98765432109",
  "cns": "987654321098765",
  "dataNascimento": "1980-03-15",
  "sexo": "MASCULINO",
  "racaCor": "BRANCA",
  "escolaridade": "SUPERIOR",
  "endereco":
    {
      "logradouro": "Avenida da Saúde",
      "numero": "450",
      "bairro": "Jardim América",
      "cidade": "São Paulo",
      "estado": "SP",
      "cep": "04532000"
    },
    "telefone": "11977776666",
    "email": "douglas.queiroz4@aluno.ce.gov.br",
    "senha": "Dv.23456",
    "dataContratacao": "2023-03-15",
    "crm": "54321-SP",
    "unidadeSaudeId": "e86a55e8-f4d2-4c02-87f5-424912d097d2"
}

> {%
    client.global.set("medico_id", response.body.id);
%}

### Listar Médicos
GET http://localhost:3000/api/medicos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6Imorc1l4RmljVjBqenZmL0kiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2djeXNyaHZ0Ym9iZWt1enBzZnd1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2Y2ZkZWFkNS1jMTI4LTRlMDEtYjQwMC01YWI5NzRlZTFlOGEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ2OTkyNDM3LCJpYXQiOjE3NDY5ODg4MzcsImVtYWlsIjoicXVlaXJvemRvdWdsYXM0NjZAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InF1ZWlyb3pkb3VnbGFzNDY2QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJub21lIjoiRG91Z2xhcyBRdWVpcm96IiwicGFwZWwiOiJBRE1JTklTVFJBRE9SX1BSSU5DSVBBTCIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNmNmZGVhZDUtYzEyOC00ZTAxLWI0MDAtNWFiOTc0ZWUxZThhIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NDY5ODg4Mzd9XSwic2Vzc2lvbl9pZCI6ImFhYjdmN2U3LTgxZTYtNGQ3Yi04ZDdhLTI5NDVhMTk4ZGE5NiIsImlzX2Fub255bW91cyI6ZmFsc2V9.xJ3QTT26NDdZnRay4WjMjjnx4rJNW1nwswGk5_bnRzs

### Listar Médico por ID
GET http://localhost:3000/api/medicos/{{medico_id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6Imorc1l4RmljVjBqenZmL0kiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2djeXNyaHZ0Ym9iZWt1enBzZnd1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2Y2ZkZWFkNS1jMTI4LTRlMDEtYjQwMC01YWI5NzRlZTFlOGEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ2OTkyNDM3LCJpYXQiOjE3NDY5ODg4MzcsImVtYWlsIjoicXVlaXJvemRvdWdsYXM0NjZAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InF1ZWlyb3pkb3VnbGFzNDY2QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJub21lIjoiRG91Z2xhcyBRdWVpcm96IiwicGFwZWwiOiJBRE1JTklTVFJBRE9SX1BSSU5DSVBBTCIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNmNmZGVhZDUtYzEyOC00ZTAxLWI0MDAtNWFiOTc0ZWUxZThhIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NDY5ODg4Mzd9XSwic2Vzc2lvbl9pZCI6ImFhYjdmN2U3LTgxZTYtNGQ3Yi04ZDdhLTI5NDVhMTk4ZGE5NiIsImlzX2Fub255bW91cyI6ZmFsc2V9.xJ3QTT26NDdZnRay4WjMjjnx4rJNW1nwswGk5_bnRzs

### Atualizar Médico
PUT http://localhost:3000/api/medicos/{{medico_id}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6Imorc1l4RmljVjBqenZmL0kiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2djeXNyaHZ0Ym9iZWt1enBzZnd1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2Y2ZkZWFkNS1jMTI4LTRlMDEtYjQwMC01YWI5NzRlZTFlOGEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ2OTkyNDM3LCJpYXQiOjE3NDY5ODg4MzcsImVtYWlsIjoicXVlaXJvemRvdWdsYXM0NjZAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InF1ZWlyb3pkb3VnbGFzNDY2QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJub21lIjoiRG91Z2xhcyBRdWVpcm96IiwicGFwZWwiOiJBRE1JTklTVFJBRE9SX1BSSU5DSVBBTCIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNmNmZGVhZDUtYzEyOC00ZTAxLWI0MDAtNWFiOTc0ZWUxZThhIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NDY5ODg4Mzd9XSwic2Vzc2lvbl9pZCI6ImFhYjdmN2U3LTgxZTYtNGQ3Yi04ZDdhLTI5NDVhMTk4ZGE5NiIsImlzX2Fub255bW91cyI6ZmFsc2V9.xJ3QTT26NDdZnRay4WjMjjnx4rJNW1nwswGk5_bnRzs

{
  "nome": "João Santos Atualizado",
  "crm": "54321-SP",
  "dataContratacao": "2023-02-01"
}

### Deletar Médico
DELETE http://localhost:3000/api/medicos/{{medico_id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6Imorc1l4RmljVjBqenZmL0kiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2djeXNyaHZ0Ym9iZWt1enBzZnd1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2Y2ZkZWFkNS1jMTI4LTRlMDEtYjQwMC01YWI5NzRlZTFlOGEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ2OTkyNDM3LCJpYXQiOjE3NDY5ODg4MzcsImVtYWlsIjoicXVlaXJvemRvdWdsYXM0NjZAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InF1ZWlyb3pkb3VnbGFzNDY2QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJub21lIjoiRG91Z2xhcyBRdWVpcm96IiwicGFwZWwiOiJBRE1JTklTVFJBRE9SX1BSSU5DSVBBTCIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNmNmZGVhZDUtYzEyOC00ZTAxLWI0MDAtNWFiOTc0ZWUxZThhIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NDY5ODg4Mzd9XSwic2Vzc2lvbl9pZCI6ImFhYjdmN2U3LTgxZTYtNGQ3Yi04ZDdhLTI5NDVhMTk4ZGE5NiIsImlzX2Fub255bW91cyI6ZmFsc2V9.xJ3QTT26NDdZnRay4WjMjjnx4rJNW1nwswGk5_bnRzs

### Login Médico (Obter Token para Testar Rotas como Médico)
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "douglas.queiroz4@aluno.ce.gov.br",
  "password": "Dv.23456"
}

> {%
    client.global.set("medico_token", response.body.access_token);
%}

###

### Obter Próprio Médico (como Médico)
GET http://localhost:3000/api/medicos/{{medico_id}}
Authorization: Bearer {{medico_token}}

###

### Listar Médicos (como Médico)
GET http://localhost:3000/api/medicos
Authorization: Bearer {{medico_token}}