### Criar Prescrição (Médico)
POST http://localhost:3000/api/prescricoes
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "pacienteId": "{{paciente_id}}",
    "unidadeSaudeId": "{{unidade_saude_id}}",
    "detalhesPrescricao": "Amoxicilina 500mg, 1 cápsula a cada 8 horas por 7 dias.",
    "cid10": "J45"
}

### Criar Prescrição (Enfermeiro, UPA)
POST https://sistema-hospitalar.onrender.com/api/prescricoes
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "pacienteId": "{{paciente_id}}",
    "unidadeSaudeId": "{{unidade_saude_id}}",
    "detalhesPrescricao": "Dipirona 500mg, 1 comprimido a cada 6 horas por 3 dias.",
    "cid10": "R51"
}

### Obter Prescrição (Médico)
GET http://localhost:3000/api/prescricoes/{{prescricao_id}}
Authorization: Bearer {{token}}

### Obter Prescrição (Enfermeiro)
GET http://localhost:3000/api/prescricoes/{{prescricao_id}}
Authorization: Bearer {{token}}

### Listar Prescrições por Paciente (Médico)
GET http://localhost:3000/api/prescricoes/pacientes/{{paciente_id}}
Authorization: Bearer {{token}}

### Listar Prescrições por Paciente (Enfermeiro)
GET http://localhost:3000/api/prescricoes/pacientes/{{paciente_id}}
Authorization: Bearer {{token}}

### Atualizar Prescrição (Médico)
PUT http://localhost:3000/api/prescricoes/{{prescricao_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "detalhesPrescricao": "Amoxicilina 500mg, 1 cápsula a cada 8 horas por 10 dias.",
  "cid10": "J45.0"
}

### Atualizar Prescrição (Enfermeiro, UPA)
PUT http://localhost:3000/api/prescricoes/{{prescricao_id_2}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "detalhesPrescricao": "Dipirona 500mg, 1 comprimido a cada 8 horas por 3 dias.",
  "cid10": "R51"
}

### Deletar Prescrição (Médico)
DELETE http://localhost:3000/api/prescricoes/{{prescricao_id}}
Authorization: Bearer {{token}}

### Gerar PDF da Prescrição (Médico)
GET http://localhost:3000/api/prescricoes/{{prescricao_id}}/pdf
Authorization: Bearer {{token}}

### Gerar PDF da Prescrição (Enfermeiro)
GET http://localhost:3000/api/prescricoes/{{prescricao_id_2}}/pdf
Authorization: Bearer {{token}}

### Gerar PDF da Prescrição (Administrador)
GET http://localhost:3000/api/prescricoes/{{prescricao_id}}/pdf
Authorization: Bearer {{token}}