### Criar Prontuário
POST https://sistema-hospitalar.onrender.com/api/prontuarios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6Imorc1l4RmljVjBqenZmL0kiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2djeXNyaHZ0Ym9iZWt1enBzZnd1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJhZjA1ZGQ1OS01MzIzLTRkYjktYTY3OS1iZjkwOGUxZWQwMzkiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzUwMzQ1NzMxLCJpYXQiOjE3NTAzNDIxMzEsImVtYWlsIjoicml6ZXB1cnBsZTlAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InJpemVwdXJwbGU5QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJub21lIjoiSm_Do28gU2FudG9zIiwicGFwZWwiOiJFTkZFUk1FSVJPIiwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiJhZjA1ZGQ1OS01MzIzLTRkYjktYTY3OS1iZjkwOGUxZWQwMzkifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc1MDM0MjEzMX1dLCJzZXNzaW9uX2lkIjoiZWE0Y2E5MGItMDU4ZS00ZDIzLWIwZTEtMWJlMjk4OTQyZWI2IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.gfsE7mpv_KBEgttIHO2z-9aC2QMd4fm6dfdDDFyEKwA

{
    "pacienteId": "{{paciente_id}}",
    "unidadeSaudeId": "{{unidade_saude_id}}",
    "descricao": "Paciente apresentou febre e tosse persistente. Realizado exame físico e solicitado raio-X de tórax.",
    "dadosAnonimizados": {
        "nome": "Paciente Anonimizado",
        "cpf": "01329538200"
    }
}

### Obter Prontuário
GET https://sistema-hospitalar.onrender.com/api/prontuarios/{{prontuario_id}}
Authorization: Bearer {{token}}

### Listar Prontuários por Paciente
GET https://sistema-hospitalar.onrender.com/api/prontuarios/pacientes/{{paciente_id}}
Authorization: Bearer {{token}}

### Atualizar Prontuário
PUT https://sistema-hospitalar.onrender.com/api/prontuarios/{{prontuario_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "descricao": "Paciente retornou com melhora dos sintomas após medicação. Raio-X normal.",
  "dadosAnonimizados": {
    "nome": "Paciente Anonimizado Atualizado",
    "cpf": "01329538200"
  }
}

### Deletar Prontuário
DELETE https://sistema-hospitalar.onrender.com/api/prontuarios/{{prontuario_id}}
Authorization: Bearer {{token}}

### Gerar PDF do Prontuário
GET https://sistema-hospitalar.onrender.com/api/prontuarios/7a051280-a49e-4d52-8213-2d6e6d10d622/pdf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6Imorc1l4RmljVjBqenZmL0kiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2djeXNyaHZ0Ym9iZWt1enBzZnd1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJhZjA1ZGQ1OS01MzIzLTRkYjktYTY3OS1iZjkwOGUxZWQwMzkiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzUwMzQ1NzMxLCJpYXQiOjE3NTAzNDIxMzEsImVtYWlsIjoicml6ZXB1cnBsZTlAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InJpemVwdXJwbGU5QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJub21lIjoiSm_Do28gU2FudG9zIiwicGFwZWwiOiJFTkZFUk1FSVJPIiwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiJhZjA1ZGQ1OS01MzIzLTRkYjktYTY3OS1iZjkwOGUxZWQwMzkifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc1MDM0MjEzMX1dLCJzZXNzaW9uX2lkIjoiZWE0Y2E5MGItMDU4ZS00ZDIzLWIwZTEtMWJlMjk4OTQyZWI2IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.gfsE7mpv_KBEgttIHO2z-9aC2QMd4fm6dfdDDFyEKwA

### Criar Prontuário (como Enfermeiro)
POST https://sistema-hospitalar.onrender.com/api/prontuarios
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "pacienteId": "{{paciente_id}}",
    "unidadeSaudeId": "{{unidade_saude_id}}",
    "descricao": "Paciente com pressão arterial elevada (140/90 mmHg). Aplicada medicação conforme prescrição.",
    "dadosAnonimizados": {
        "nome": "Paciente Anonimizado",
        "cpf": "01329538200"
    }
}

### Obter Prontuário (como Enfermeiro)
GET https://sistema-hospitalar.onrender.com/api/prontuarios/{{prontuario_id_2}}
Authorization: Bearer {{token}}

### Listar Prontuários por Paciente (como Enfermeiro)
GET https://sistema-hospitalar.onrender.com/api/prontuarios/pacientes/{{paciente_id}}
Authorization: Bearer {{token}}

### Gerar PDF do Prontuário (como Enfermeiro)
GET https://sistema-hospitalar.onrender.com/api/prontuarios/{{prontuario_id_2}}/pdf
Authorization: Bearer {{token}}