### Criação de Unidade de Saúde
POST https://sistema-hospitalar.onrender.com/api/unidades-saude
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6Imorc1l4RmljVjBqenZmL0kiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2djeXNyaHZ0Ym9iZWt1enBzZnd1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2Y2ZkZWFkNS1jMTI4LTRlMDEtYjQwMC01YWI5NzRlZTFlOGEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ2OTg4NzQ4LCJpYXQiOjE3NDY5ODUxNDgsImVtYWlsIjoicXVlaXJvemRvdWdsYXM0NjZAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InF1ZWlyb3pkb3VnbGFzNDY2QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJub21lIjoiRG91Z2xhcyBRdWVpcm96IiwicGFwZWwiOiJBRE1JTklTVFJBRE9SX1BSSU5DSVBBTCIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNmNmZGVhZDUtYzEyOC00ZTAxLWI0MDAtNWFiOTc0ZWUxZThhIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NDY5ODUxNDh9XSwic2Vzc2lvbl9pZCI6Ijc0OGQyNDk1LTU5YmUtNDQzZC05YjNjLTMxZTk1YTUzNDg4OSIsImlzX2Fub255bW91cyI6ZmFsc2V9.PFiHuQ96B5SwaezfSjOWgUZGf_Zum-9EGCix5E9yYqU

{
  "nome": "Hospital Central",
  "tipo": "HOSPITAL",
  "cnes": "1234567",
  "endereco": {
    "logradouro": "Rua Principal",
    "numero": "100",
    "bairro": "Centro",
    "cidade": "São Paulo",
    "estado": "SP",
    "cep": "12345000"
  },
  "telefone": "11999999999",
  "servicosEssenciais": [
    "Atendimento de emergência",
    "Internação"
  ],
  "servicosAmpliados": [
    "Cirurgia"
  ]
}

### Listar Unidades de Saúde
GET https://sistema-hospitalar.onrender.com/api/unidades-saude
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6Imorc1l4RmljVjBqenZmL0kiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2djeXNyaHZ0Ym9iZWt1enBzZnd1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2Y2ZkZWFkNS1jMTI4LTRlMDEtYjQwMC01YWI5NzRlZTFlOGEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ2OTg4NzQ4LCJpYXQiOjE3NDY5ODUxNDgsImVtYWlsIjoicXVlaXJvemRvdWdsYXM0NjZAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InF1ZWlyb3pkb3VnbGFzNDY2QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJub21lIjoiRG91Z2xhcyBRdWVpcm96IiwicGFwZWwiOiJBRE1JTklTVFJBRE9SX1BSSU5DSVBBTCIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNmNmZGVhZDUtYzEyOC00ZTAxLWI0MDAtNWFiOTc0ZWUxZThhIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NDY5ODUxNDh9XSwic2Vzc2lvbl9pZCI6Ijc0OGQyNDk1LTU5YmUtNDQzZC05YjNjLTMxZTk1YTUzNDg4OSIsImlzX2Fub255bW91cyI6ZmFsc2V9.PFiHuQ96B5SwaezfSjOWgUZGf_Zum-9EGCix5E9yYqU

### Listar Funcionários
GET https://sistema-hospitalar.onrender.com/api/unidades-saude/3e1739f5-2439-4db6-9f4c-9388e3777fa9/funcionarios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6Imorc1l4RmljVjBqenZmL0kiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2djeXNyaHZ0Ym9iZWt1enBzZnd1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2Y2ZkZWFkNS1jMTI4LTRlMDEtYjQwMC01YWI5NzRlZTFlOGEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ2OTg4NzQ4LCJpYXQiOjE3NDY5ODUxNDgsImVtYWlsIjoicXVlaXJvemRvdWdsYXM0NjZAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InF1ZWlyb3pkb3VnbGFzNDY2QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJub21lIjoiRG91Z2xhcyBRdWVpcm96IiwicGFwZWwiOiJBRE1JTklTVFJBRE9SX1BSSU5DSVBBTCIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNmNmZGVhZDUtYzEyOC00ZTAxLWI0MDAtNWFiOTc0ZWUxZThhIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NDY5ODUxNDh9XSwic2Vzc2lvbl9pZCI6Ijc0OGQyNDk1LTU5YmUtNDQzZC05YjNjLTMxZTk1YTUzNDg4OSIsImlzX2Fub255bW91cyI6ZmFsc2V9.PFiHuQ96B5SwaezfSjOWgUZGf_Zum-9EGCix5E9yYqU

### Atualizar Unidade de Saúde
PUT https://sistema-hospitalar.onrender.com/api/unidades-saude/3e1739f5-2439-4db6-9f4c-9388e3777fa9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6Imorc1l4RmljVjBqenZmL0kiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2djeXNyaHZ0Ym9iZWt1enBzZnd1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2Y2ZkZWFkNS1jMTI4LTRlMDEtYjQwMC01YWI5NzRlZTFlOGEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ2OTg4NzQ4LCJpYXQiOjE3NDY5ODUxNDgsImVtYWlsIjoicXVlaXJvemRvdWdsYXM0NjZAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InF1ZWlyb3pkb3VnbGFzNDY2QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJub21lIjoiRG91Z2xhcyBRdWVpcm96IiwicGFwZWwiOiJBRE1JTklTVFJBRE9SX1BSSU5DSVBBTCIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNmNmZGVhZDUtYzEyOC00ZTAxLWI0MDAtNWFiOTc0ZWUxZThhIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NDY5ODUxNDh9XSwic2Vzc2lvbl9pZCI6Ijc0OGQyNDk1LTU5YmUtNDQzZC05YjNjLTMxZTk1YTUzNDg4OSIsImlzX2Fub255bW91cyI6ZmFsc2V9.PFiHuQ96B5SwaezfSjOWgUZGf_Zum-9EGCix5E9yYqU

{
  "nome": "Hospital Central Atualizado",
  "tipo": "HOSPITAL",
  "cnes": "1234567",
  "endereco": {
    "logradouro": "Rua Principal Atualizada",
    "numero": "200",
    "bairro": "Centro Atualizado",
    "cidade": "São Paulo Atualizado",
    "estado": "SP",
    "cep": "12345001"
  },
  "telefone": "11999999998",
  "servicosEssenciais": [
    "Atendimento de emergência atualizado",
    "Internação atualizada"
  ],
  "servicosAmpliados": [
    "Cirurgia atualizada"
  ]
}

### Buscar Unidade de Saúde por ID
GET https://sistema-hospitalar.onrender.com/api/unidades-saude/3e1739f5-2439-4db6-9f4c-9388e3777fa9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6Imorc1l4RmljVjBqenZmL0kiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2djeXNyaHZ0Ym9iZWt1enBzZnd1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2Y2ZkZWFkNS1jMTI4LTRlMDEtYjQwMC01YWI5NzRlZTFlOGEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ2OTg4NzQ4LCJpYXQiOjE3NDY5ODUxNDgsImVtYWlsIjoicXVlaXJvemRvdWdsYXM0NjZAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InF1ZWlyb3pkb3VnbGFzNDY2QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJub21lIjoiRG91Z2xhcyBRdWVpcm96IiwicGFwZWwiOiJBRE1JTklTVFJBRE9SX1BSSU5DSVBBTCIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNmNmZGVhZDUtYzEyOC00ZTAxLWI0MDAtNWFiOTc0ZWUxZThhIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NDY5ODUxNDh9XSwic2Vzc2lvbl9pZCI6Ijc0OGQyNDk1LTU5YmUtNDQzZC05YjNjLTMxZTk1YTUzNDg4OSIsImlzX2Fub255bW91cyI6ZmFsc2V9.PFiHuQ96B5SwaezfSjOWgUZGf_Zum-9EGCix5E9yYqU

### Deletar Unidade de Saúde
DELETE https://sistema-hospitalar.onrender.com/api/unidades-saude/3e1739f5-2439-4db6-9f4c-9388e3777fa9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6Imorc1l4RmljVjBqenZmL0kiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2djeXNyaHZ0Ym9iZWt1enBzZnd1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2Y2ZkZWFkNS1jMTI4LTRlMDEtYjQwMC01YWI5NzRlZTFlOGEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ2OTg4NzQ4LCJpYXQiOjE3NDY5ODUxNDgsImVtYWlsIjoicXVlaXJvemRvdWdsYXM0NjZAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InF1ZWlyb3pkb3VnbGFzNDY2QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJub21lIjoiRG91Z2xhcyBRdWVpcm96IiwicGFwZWwiOiJBRE1JTklTVFJBRE9SX1BSSU5DSVBBTCIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNmNmZGVhZDUtYzEyOC00ZTAxLWI0MDAtNWFiOTc0ZWUxZThhIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NDY5ODUxNDh9XSwic2Vzc2lvbl9pZCI6Ijc0OGQyNDk1LTU5YmUtNDQzZC05YjNjLTMxZTk1YTUzNDg4OSIsImlzX2Fub255bW91cyI6ZmFsc2V9.PFiHuQ96B5SwaezfSjOWgUZGf_Zum-9EGCix5E9yYqU

### Associar Funcionário a Unidade de Saúde
POST https://sistema-hospitalar.onrender.com/api/unidades-saude/:unidadeSaudeId/funcionarios/:funcionarioId
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6Imorc1l4RmljVjBqenZmL0kiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2djeXNyaHZ0Ym9iZWt1enBzZnd1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2Y2ZkZWFkNS1jMTI4LTRlMDEtYjQwMC01YWI5NzRlZTFlOGEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ2OTg4NzQ4LCJpYXQiOjE3NDY5ODUxNDgsImVtYWlsIjoicXVlaXJvemRvdWdsYXM0NjZAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InF1ZWlyb3pkb3VnbGFzNDY2QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJub21lIjoiRG91Z2xhcyBRdWVpcm96IiwicGFwZWwiOiJBRE1JTklTVFJBRE9SX1BSSU5DSVBBTCIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNmNmZGVhZDUtYzEyOC00ZTAxLWI0MDAtNWFiOTc0ZWUxZThhIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NDY5ODUxNDh9XSwic2Vzc2lvbl9pZCI6Ijc0OGQyNDk1LTU5YmUtNDQzZC05YjNjLTMxZTk1YTUzNDg4OSIsImlzX2Fub255bW91cyI6ZmFsc2V9.PFiHuQ96B5SwaezfSjOWgUZGf_Zum-9EGCix5E9yYqU
