### Criação de Unidade de Saúde
POST https://sistema-hospitalar.onrender.com/api/unidades-saude
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Hospital Central",
  "tipo": "HOSPITAL",
  "cnes": "1234567",
  "endereco": {
    "logradouro": "Rua Principal",
    "numero": "100",
    "bairro": "Centro",
    "cidade": "São Paulo",
    "estado": "SP",
    "cep": "12345000"
  },
  "telefone": "11999999999",
  "servicosEssenciais": [
    "Atendimento de emergência",
    "Internação"
  ],
  "servicosAmpliados": [
    "Cirurgia"
  ]
}

### Listar Unidades de Saúde
GET https://sistema-hospitalar.onrender.com/api/unidades-saude
Authorization: Bearer {{token}}

### Listar Funcionários
GET https://sistema-hospitalar.onrender.com/api/unidades-saude/{{unidade_saude_id}}/funcionarios
Authorization: Bearer {{token}}

### Atualizar Unidade de Saúde
PUT https://sistema-hospitalar.onrender.com/api/unidades-saude/{{unidade_saude_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Hospital Central Atualizado",
  "tipo": "HOSPITAL",
  "cnes": "1234567",
  "endereco": {
    "logradouro": "Rua Principal Atualizada",
    "numero": "200",
    "bairro": "Centro Atualizado",
    "cidade": "São Paulo Atualizado",
    "estado": "SP",
    "cep": "12345001"
  },
  "telefone": "11999999998",
  "servicosEssenciais": [
    "Atendimento de emergência atualizado",
    "Internação atualizada"
  ],
  "servicosAmpliados": [
    "Cirurgia atualizada"
  ]
}

### Buscar Unidade de Saúde por ID
GET https://sistema-hospitalar.onrender.com/api/unidades-saude/{{unidade_saude_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Deletar Unidade de Saúde
DELETE https://sistema-hospitalar.onrender.com/api/unidades-saude/{{unidade_saude_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Associar Funcionário a Unidade de Saúde
POST https://sistema-hospitalar.onrender.com/api/unidades-saude/{{unidade_saude_id}}/funcionarios/{{funcionario_id}}
Content-Type: application/json
Authorization: Bearer {{token}}
