### Criação de Unidade de Saúde
POST http://localhost:3000/api/unidades-saude
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IlFPQzlqMXFKZzZZSDdqKzQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2lpZXJ4ZXVwcWhub3Fxc2tzZ3hlLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlZjM1ZTEyNy0xZDIwLTRkYTEtYjg2OS01YWYwZWQ2NzRjMDAiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY2MTcxNTc1LCJpYXQiOjE3NjYxNjc5NzUsImVtYWlsIjoicXVlaXJvemRvdWdsYXM0NjZAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InF1ZWlyb3pkb3VnbGFzNDY2QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJub21lIjoiRG91Z2xhcyBRdWVpcm96IiwicGFwZWwiOiJBRE1JTklTVFJBRE9SX1BSSU5DSVBBTCIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiZWYzNWUxMjctMWQyMC00ZGExLWI4NjktNWFmMGVkNjc0YzAwIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NjYxNjc5NzV9XSwic2Vzc2lvbl9pZCI6IjAyMDA1NTNjLTAwYjMtNGVjZC04YzI4LTY2Mjk5MTlhNmU3YiIsImlzX2Fub255bW91cyI6ZmFsc2V9.J_27u6rN5GrvXOcM-9zPH0wYaomPBkHDkqRc-s8nui0

{
  "nome": "Hospital Central",
  "tipo": "HOSPITAL",
  "cnes": "1234567",
  "endereco": {
    "logradouro": "Rua Principal",
    "numero": "100",
    "bairro": "Centro",
    "cidade": "São Paulo",
    "estado": "SP",
    "cep": "12345000"
  },
  "telefone": "11999999999",
  "servicosEssenciais": [
    "Atendimento de emergência",
    "Internação"
  ],
  "servicosAmpliados": [
    "Cirurgia"
  ]
}

### Listar Unidades de Saúde
GET http://localhost:3000/api/unidades-saude
Authorization: Bearer {{token}}

### Listar Funcionários
GET http://localhost:3000/api/unidades-saude/{{unidade_saude_id}}/funcionarios
Authorization: Bearer {{token}}

### Atualizar Unidade de Saúde
PUT http://localhost:3000/api/unidades-saude/{{unidade_saude_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Hospital Central Atualizado",
  "tipo": "HOSPITAL",
  "cnes": "1234567",
  "endereco": {
    "logradouro": "Rua Principal Atualizada",
    "numero": "200",
    "bairro": "Centro Atualizado",
    "cidade": "São Paulo Atualizado",
    "estado": "SP",
    "cep": "12345001"
  },
  "telefone": "11999999998",
  "servicosEssenciais": [
    "Atendimento de emergência atualizado",
    "Internação atualizada"
  ],
  "servicosAmpliados": [
    "Cirurgia atualizada"
  ]
}

### Buscar Unidade de Saúde por ID
GET http://localhost:3000/api/unidades-saude/{{unidade_saude_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Deletar Unidade de Saúde
DELETE http://localhost:3000/api/unidades-saude/{{unidade_saude_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Associar Funcionário a Unidade de Saúde
POST https://sistema-hospitalar.onrender.com/api/unidades-saude/{{unidade_saude_id}}/funcionarios/{{funcionario_id}}
Content-Type: application/json
Authorization: Bearer {{token}}
