name: Ping for HMS

on:
  schedule:
    - cron: '*/5 * * * *'  # A cada 5 minutos (UTC)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Executar ping
        run: node dist/index.js
        env:
          PING_URL: https://sistema-hospitalar.onrender.com
