# ping a cada 5 minutos em https://sistema-hospitalar.onrender.com
name: Ping for HMS

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the server is up
        run: curl -f https://sistema-hospitalar.onrender.com || exit 1